### ISSUE TITLE
Mock up Batch GUI

### ISSUE THREAD

**Issue by mr-feek** [fpm5022/412ProjectGrader#26]
We can use this issue to discuss what features/components we would like in the BatchGUI

**Comment by joshmillerday** [comment]
Right now I believe we need

File Chooser Button (Zips)
Output location button
Input file Location
Compile Button

What else is necessary?

**Comment by mr-feek** [comment]
- Is the file chooser button the directory which contains all of the students zipped files? We might want to abstract out the process of unzipping the files and leave that up to the user.
- Is the output location the directory in which all of the students outputs will be stored in various text files?
- I don't think we'll be able to use file chooser for input file location, as this absolute path will be different for every student. It may be easier to have a text field for the name of the main class.
- Are we getting rid of the idea of having a list of the student's names and checkboxes to select which students to test?

**Comment by joshmillerday** [comment]
The output location would just be where the single text file went but that wont be a problem to just have it go to a default place.

Im not sure of the process to access the files is. Is there a method to display them graphically on the GUI? Would adding the checkbox functionality take a lot of effort?
